### PR TITLE
Merge panels into one.

### PR DESCRIPTION
**Pull request by Oxervision**
Hi, the first thanks for the addon!!

I would like, if this is possible, to have all different panels merge into one, so the UI would be more clean.

Panels

Something like this:

Merged Panels

Thanks in advance!!

### CODE REVIEW

**Comment by kevancress** [comment]
Hey @Oxervision 

This is a really great suggestion, and the mock-up looks great!

Have you actually made changes to the code to implement this? If yes, I think there's an issue with the pull request, since it's just showing my commits from the version 0.5 branch

If it's just mock-up then the issues section (https://github.com/kevancress/MeasureIt_ARCH/issues) would be the right place for the suggestion.

**Comment by Oxervision** [comment]
Hi kevancress,

I donwloaded the code (v0.4.6) and I made the changes to the files in my computer, I don't know very well how Github works, so if you could  explain to me how I can share this changes, I will be very grateful.

**Comment by kevancress** [comment]
Hi @Oxervision (sorry about the slow reply)

If you want, you can just your changed version of the files as a .zip folder here and I can add in the changes. (I'll be sure to credit you for them in the commit.)

For git to track the changes you need to clone the repository either using git directly in the command line, or with [github desktop](https://desktop.github.com/)

**Comment by Oxervision** [comment]
Hi again, 

• The green files are the modified:

modified files

• Here the .zip modified addon:

[MeasureIt_ARCH.zip](https://github.com/kevancress/MeasureIt_ARCH/files/5501426/MeasureIt_ARCH.zip)

I changed some files to reorganize the panels, add MT  to some classes , and to change the "=" sign for  ":" in a Property.
There is a minor problem, each you run Blender the sub-panels are in different position, I don't know why, I'm not an expert with Python.

**Comment by kevancress** [comment]
Fantastic, I've added the changes to this branch: https://github.com/kevancress/MeasureIt_ARCH/tree/Oxervision-Panel-Changes

I'll do some testing today, and I'm going to make some minor tweaks to keep the Icons consistent with the rest of the addon, and see if I can find out why the sub-panels switch positions. Once I've done that I'll add this to the Master branch!!

Thanks so much for sending in these changes! It really cleans up the UI and is super helpful!!!!!!

**Comment by kevancress** [comment]
Alright, I've merged your changes into the master branch! Thanks Again!

**Pull request closed without merging**
