### PR TITLE
Rewritten unit formatting

### PR DESCRIPTION
**Pull request by mjepronk**
Hi Kevan,

Sorry, I've another big PR... It seems that something went wrong when merging my previous PR. So I redid some code cleanup. If you are having merge issues let me know, I'll take care of them.

I've also improved the code for formatting distances, area and angles. Hope you like it. Let me know if there's something wrong. I've added some tests, but these could be improved.

### CODE REVIEW

**Comment by mjepronk** [comment]
Hold on, I'm rebasing now...

**Comment by kevancress** [comment]
Hey @mjepronk 

Yeah I think I messed up some of the code cleanup when bringing the last PR's to the Dev branch, Thanks for fixing that.

I'm testing now, just fixing a couple of argument errors from some functions and operators.

The new unit formatting code looks great, way cleaner and simpler than what I had! There does seem to be an issue with the Imperial precision though (gif below showing a comparision with the current dev). It seems to always be outputting a result that is less than the actual measurement.


imperial precision

**Comment by kevancress** [comment]
fixed it,  INCH_TO_CM should have been 2.54 not 2.56, Merging now!

**Comment by mjepronk** [comment]
Oops, sorry for that! Thanks for merging!

**Pull request merged**
