### PR TITLE
Cosmetic changes:

### PR DESCRIPTION
**Pull request by mjepronk**
- Removed trailing whitespace
- PEP8
- Remove `is False`, `is True`, `is not ''`, etc.
- Remove some usage of `eval`
- Fixed spelling errors
- Reordered imports
- Removed unused imports

### CODE REVIEW

**Comment by mjepronk** [comment]
There is still more work to do:
- There are files that are missing the GPL header
- There are still many warnings from flake8 ( unused symbols etc.)

**Comment by mjepronk** [comment]
Sorry that it's such a huge diff... Hope you appreciate it anyway! :-)

**Comment by kevancress** [comment]
Hey @mjepronk this is great!! I'll take a look through this today and get it merged!

**Comment by kevancress** [comment]
Awesome, merging now!

**Comment by kevancress** [comment]
Hey @mjepronk,

Just out of curiosity, what's the issue with using eval() in this application? I know it can create lots of security vulnerabilities when used with unmodified user input... but I'm mostly using it to pass Blender API data paths to operators within the addon.

Are there other security concerns / issues that could be a problem here?

**Comment by mjepronk** [comment]
Hi Kevan,

Not a dumb question at all (if such a thing exists).

While it's true that your use of `eval` does not create any security problems, I still discourage using `eval`.

The reasons are:
- It's not amenable to static analysis (such as flake8, etc.)
- It makes the code slightly more complicated to follow/understand
- It shouldn't be necessary in Python (there's getattr, etc.)

That said it's interesting how you use it, it reminds me of lenses/optics in Haskell (which are basically a getter and a setter in one "object").

Having said that, let's keep the remaining `eval` for now, we'll tackle that later. I'm currently finding my way through the code, in order to see what improvements I can make. And I will continue creating PR's coming weeks.

Kind regards,
- Matthias

**Pull request merged**
